### ISSUE TITLE
牛皮

### ISSUE THREAD

**Issue by MenMensAa** [yingmanwumen/BUPT_nCov_Auto_clockIn#3]
怎么试出来的表单内容，拼音可太秀了

**Comment by yingmanwumen** [comment]
> 怎么试出来的表单内容，拼音可太秀了
@MenMensAa 
太久了忘了，当初好像是爬虫爬的，爬到的时候一脸懵逼，好在一部分字段在代码的其他地方留了注释。剩下没留注释的字段，大概只有写的人知道是什么意思了。
