### ISSUE TITLE
好像现在无法打卡了？

### ISSUE THREAD

**Issue by why724809024** [yingmanwumen/BUPT_nCov_Auto_clockIn#4]
好像CAS认证那一步报错了。response.content是"Application Not Authorized to Use CAS"

**Comment by yingmanwumen** [comment]
> 好像CAS认证那一步报错了。response.content是"Application Not Authorized to Use CAS"

是的，学校换了个CAS服务（也有可能是把疫情打卡的CAS服务关了？）我刚刚睡醒，不太清楚，不好意思

**Comment by why724809024** [comment]
> 

好的，谢谢~我也再研究一下，应该还有救，TG上的打卡bot还能正常用

**Comment by why724809024** [comment]
好像这里改一下就行了：
SERVICE = 'https://app.bupt.edu.cn/a_bupt/api/sso/cas?redirect=https%253A%252F%252Fapp.bupt.edu.cn%252Fncov%252Fwap%252Fdefault%252Fsave%26from%3Dwap'

**Comment by yingmanwumen** [comment]
> 好像这里改一下就行了：
> SERVICE = 'https://app.bupt.edu.cn/a_bupt/api/sso/cas?redirect=https%253A%252F%252Fapp.bupt.edu.cn%252Fncov%252Fwap%252Fdefault%252Fsave%26from%3Dwap'
> 

你试过了吗？昨天晚上按照这个还是不可以的……我这就试试

**Comment by why724809024** [comment]
> 

刚试过确实可以，我也不知道......很玄学

**Comment by why724809024** [comment]
> > 好像这里改一下就行了：
> > SERVICE = 'https://app.bupt.edu.cn/a_bupt/api/sso/cas?redirect=https%253A%252F%252Fapp.bupt.edu.cn%252Fncov%252Fwap%252Fdefault%252Fsave%26from%3Dwap'
> 
> 你试过了吗？昨天晚上按照这个还是不可以的……我这就试试

刚试过确实可以，我也不知道......很玄学

**Comment by yingmanwumen** [comment]
> > > 好像这里改一下就行了：
> > > SERVICE = 'https://app.bupt.edu.cn/a_bupt/api/sso/cas?redirect=https%253A%252F%252Fapp.bupt.edu.cn%252Fncov%252Fwap%252Fdefault%252Fsave%26from%3Dwap'
> > 
> > 
> > 你试过了吗？昨天晚上按照这个还是不可以的……我这就试试
> 
> 刚试过确实可以，我也不知道......很玄学

OK，我还在安装`vim`的`python`插件……你有兴趣提交一个PR吗？很乐意看到您的参与。

**Comment by why724809024** [comment]
> > > > 好像这里改一下就行了：
> > > > SERVICE = 'https://app.bupt.edu.cn/a_bupt/api/sso/cas?redirect=https%253A%252F%252Fapp.bupt.edu.cn%252Fncov%252Fwap%252Fdefault%252Fsave%26from%3Dwap'
> > > 
> > > 
> > > 你试过了吗？昨天晚上按照这个还是不可以的……我这就试试
> > 
> > 
> > 刚试过确实可以，我也不知道......很玄学
> 
> OK，我还在安装`vim`的`python`插件……你有兴趣提交一个PR吗？很乐意看到您的参与。

好的，这还是我第一次PR，尝试一下hhhh

**Comment by why724809024** [comment]
已经提交PR~很高兴参与进来，您的脚本也帮了我很大的忙^_^

**Comment by yingmanwumen** [comment]
> 已经提交PR~很高兴参与进来，您的脚本也帮了我很大的忙^_^

不用客气，在应对无端的形式主义时脚本就是非暴力的抵抗～

Have a nice day~
